"use client";

import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  AlertTriangle,
  Brain,
  Lightbulb,
  TrendingUp,
  Zap,
} from "lucide-react";

const insights = [
  {
    type: "hotspot",
    icon: AlertTriangle,
    color: "text-red-500",
    bg: "bg-red-50 dark:bg-red-900/20",
    title: "Emerging Water Crisis in Pindra Block",
    description:
      "45 submissions in 72 hours report water contamination. AI detects cluster pattern consistent with groundwater contamination event. Recommend immediate water quality testing and temporary supply arrangements.",
    confidence: 94,
    urgency: "critical",
  },
  {
    type: "prediction",
    icon: TrendingUp,
    color: "text-purple-500",
    bg: "bg-purple-50 dark:bg-purple-900/20",
    title: "Monsoon Preparedness Gap Detected",
    description:
      "Based on 3-year trend analysis, flood-related submissions increase 340% during Jul-Sep. Current drainage infrastructure in Harahua and Ramnagar is inadequate. Recommend pre-monsoon drainage clearance project (est. ₹12L).",
    confidence: 87,
    urgency: "high",
  },
  {
    type: "recommendation",
    icon: Lightbulb,
    color: "text-amber-500",
    bg: "bg-amber-50 dark:bg-amber-900/20",
    title: "Scheme Co-funding Opportunity: PMKSY",
    description:
      "3 proposed irrigation projects are eligible for PM Krishi Sinchayee Yojana. Combined co-funding potential of ₹1.8 Cr could reduce MPLADS burden by 65% for agriculture sector projects.",
    confidence: 91,
    urgency: "medium",
  },
  {
    type: "optimization",
    icon: Brain,
    color: "text-indigo-500",
    bg: "bg-indigo-50 dark:bg-indigo-900/20",
    title: "Budget Reallocation Suggestion",
    description:
      "Digital infrastructure has lowest citizen demand (4%) but 5% budget allocation. Reallocating ₹25L from digital to healthcare (24% demand, 18% budget) would improve demand-budget alignment by 15%.",
    confidence: 82,
    urgency: "medium",
  },
  {
    type: "impact",
    icon: Zap,
    color: "text-emerald-500",
    bg: "bg-emerald-50 dark:bg-emerald-900/20",
    title: "High-Impact Quick Win Identified",
    description:
      "Solar street light repairs in Pindra (est. ₹3.5L, 2-week timeline) would address 45 submissions and benefit 5,700 households. Cost-per-beneficiary ratio of ₹6.14 makes this the most efficient proposed intervention.",
    confidence: 96,
    urgency: "low",
  },
];

export function AIInsights() {
  return (
    <Card className="animate-slide-up" style={{ animationDelay: "400ms" }}>
      <CardHeader>
        <div className="flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary-100 dark:bg-primary-900/30">
            <Brain className="h-4 w-4 text-primary-600" />
          </div>
          <div>
            <CardTitle>AI Intelligence Insights</CardTitle>
            <p className="text-[10px] text-[var(--text-tertiary)]">
              Auto-generated by Decision Intelligence Engine
            </p>
          </div>
        </div>
      </CardHeader>

      <div className="space-y-3">
        {insights.map((insight, i) => (
          <div
            key={i}
            className={`rounded-xl ${insight.bg} p-4 transition-all duration-200 hover:shadow-[var(--shadow-sm)]`}
          >
            <div className="flex items-start gap-3">
              <insight.icon className={`mt-0.5 h-5 w-5 shrink-0 ${insight.color}`} />
              <div className="min-w-0 flex-1">
                <div className="flex items-start justify-between gap-2">
                  <h4 className="text-sm font-semibold text-[var(--text-primary)]">
                    {insight.title}
                  </h4>
                  <Badge
                    variant={
                      insight.urgency === "critical" ? "danger" :
                      insight.urgency === "high" ? "warning" :
                      insight.urgency === "medium" ? "info" : "success"
                    }
                    size="sm"
                  >
                    {insight.urgency}
                  </Badge>
                </div>
                <p className="mt-1.5 text-xs leading-relaxed text-[var(--text-secondary)]">
                  {insight.description}
                </p>
                <div className="mt-2 flex items-center gap-3">
                  <span className="text-[10px] font-medium text-[var(--text-tertiary)]">
                    AI Confidence: {insight.confidence}%
                  </span>
                  <div className="h-1.5 w-20 overflow-hidden rounded-full bg-[var(--bg-tertiary)]">
                    <div
                      className="h-full rounded-full bg-primary-500 transition-all duration-700"
                      style={{ width: `${insight.confidence}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
}
